### ISSUE TITLE
Push the newest version to the repo

### ISSUE THREAD

**Issue by Wikiwix** [gaaclarke/pmap#1]
The release `0.2.1` is not available in the repo. Could you please push the current version here too?

Background is that I am at least considering to make the package null-safe (and improve readability of the code if that is welcome too)

**Comment by Wikiwix** [comment]
I already made the improvements I had in mind [in a feature branch of my fork](https://github.com/Wikiwix/pmap/tree/feature/nullsafety). It came up, that the current release version has issues with the buffer implementation. Those are fixed with my changes as well.

Once you push the newest version I can rebase. I hope you are interested in my changes :).

**Comment by gaaclarke** [comment]
Cool thanks, pushed.

**Comment by Wikiwix** [comment]
> Cool thanks, pushed.

Thanks a lot.  #2 is already ready for review :)
